#!/bin/bash
#
# decompose

# Parse parameters and run the correct command.
#
# Parameters:
#   $1: decompose parameters
decompose-parse-parameters() {
  case $1 in
    "--init")
      decompose-init-command $2;;
    "--update")
      decompose-update-environment;;
    "--build")
      decompose-build;;
    "--version")
      decompose-version;;
    "--help")
      decompose-print-help;;
    *)
      # Go through all environment commands
      local decompose_directory
      decompose-find-decompose-directory decompose_directory

      if [ -f $decompose_directory/environment/processes ]; then
        . $decompose_directory/environment/processes
        for p in "${DECOMPOSE_PROCESSES[@]}"
        do
          if [ "$1" == "$p" ]; then
            decompose-load-elements
            $p "${@:2}"
            exit 0
          fi
        done
      fi

      echo "Unknown parameter '$1'"
      decompose-print-help
      ;;
  esac
}

# Print help
decompose-print-help() {
  cat <<HELP_EOF
decompose - Development Environment Compose

Core commands:

--init <git_url>
  Initialize an environment from a git URL and name
--update
  Update the current environment
--build
  Build project files from templates
--version
  Print version
--help
  This message
HELP_EOF

  # Go through all environment commands
  local decompose_directory
  decompose-find-decompose-directory decompose_directory

  if [ -f $decompose_directory/environment/processes ]; then
    echo -e "\nEnvironment processes:\n"

    . $decompose_directory/environment/processes
    for p in "${DECOMPOSE_PROCESSES[@]}"; do
      echo "$p"
      "$p"_help
    done
  fi
}

# Return md5 hash of parameter $1
#
# Parameters:
#   $1: string to hash
#   $2: hash value returned
decompose-md5-hash() {
  local string_value=$1
  local hash_value=$2

  #echo "$environment_url whatever"
  local _hash=$(echo "$string_value" | md5sum)
  eval "$hash_value=${_hash% -*}"
}

# Initialize the environment (.decompose directory)
#
# Paramaters:
#   $1: environment url
decompose-init-environment() {
  local environment_url=$1

  # Is environment parameter valid?
  if [ -z "$environment_url" ]; then
    echo "Please supply an environment url to initialize"
    return 1
  fi

  # Clone (or update) the environment
  local decompose_data_dir=$(realpath ~/.local/share/decompose)
  local environment_hash
  decompose-md5-hash $environment_url environment_hash

  # If the directory exists then try to update the repository or else clone
  if [ -d "$decompose_data_dir/ecosphere/$environment_hash" ]; then
    git -C $decompose_data_dir/ecosphere/$environment_hash pull
  else
    git clone $environment_url \
      $decompose_data_dir/ecosphere/$environment_hash
  fi

  # Copy files from clone to .decompose
  # Is environment created already?
  local decompose_directory
  decompose-find-decompose-directory decompose_directory
  if [ -d "$decompose_directory" ]; then
    echo ".decompose directory already exists here:"
    echo "$decompose_directory"
    exit 1
  fi

  echo "Initializing environment"
  mkdir ".decompose"

  # Save decompose environment
  cat <<ENV_FILE > .decompose-init
$environment_url
ENV_FILE

  # Copy environment files
  mkdir ".decompose/environment"
  cp -r $decompose_data_dir/ecosphere/$environment_hash/* .decompose/environment
}

# Initialize environment command
#
# Paramaters:
#   $1: environment url
decompose-init-command() {
  local environment_url=$1

  # Is environment parameter valid?
  if [ -z "$environment_url" ]; then
    echo "Please supply an environment url to initialize"
    exit 1
  fi

  # Create environment
  decompose-init-environment $environment_url

  # If error occured then quit
  if [ "$?" -gt "0" ]; then
    echo "Error occured initializing environment"
    exit 1
  fi

  # Copy skeleton to working directory
  cp -r .decompose/environment/skel/. ./
}

# Return 0 if .decompose exists, else return 1
decompose-directory-exists() {
  local decompose_directory
  decompose-find-decompose-directory decompose_directory

  # If .decompose is missing then return error code.
  if [ "$?" -gt "0"  ]; then
    return 1
  fi

  return 0
}

# Load elements
decompose-load-elements() {
  local decompose_directory
  decompose-find-decompose-directory decompose_directory

  # Load default settings and then overrides
  . $decompose_directory/environment/elements
  if [ -e $decompose_directory/elements ]; then
    . $decompose_directory/elements
  fi
}

# Updates decompose environment
decompose-update-environment() {
  # If .decompose-init doesn't exist then there is nothing we can do
  local project_root
  decompose-project-root project_root
  if [ ! -e "$project_root/.decompose-init" ]; then
    echo "Cannot update '.decompose' because '.decompose-init' is missing"
    echo "Create a '.decompose-init' file with the URL to the environment URL"
    echo "Or delete the '.decompose' directory and run 'decompose --init' again"
    exit 1
  fi

  # If decompose directory doesn't exist initialize .decompose directory
  decompose-directory-exists
  if [ "$?" -gt "0" ]; then
    local environment_url=$(cat "$project_root/.decompose-init")

    # Initialize .decompose
    decompose-init-environment $environment_url

    return "$?"
  fi

  local decompose_data_dir=$(realpath ~/.local/share/decompose)
  local decompose_directory
  decompose-find-decompose-directory decompose_directory

  # Update git repository
  local environment_url=$(cat "$project_root/.decompose-init")
  local environment_hash
  decompose-md5-hash $environment_url environment_hash
  git -C "$decompose_data_dir/ecosphere/$environment_hash" pull

  # Update environment
  if [ -n $decompose_directory ]; then
    rm -r $decompose_directory/environment
    mkdir -p $decompose_directory/environment
  fi
  cp -r $decompose_data_dir/ecosphere/$environment_hash/* \
    $decompose_directory/environment
}

# Build project files from templates
decompose-build() {
  echo "Building project files from templates"
  # Find all .mo files
  local project_root
  decompose-project-root project_root
  local templates=(
    $(find $project_root -path "$project_root/.decompose" -prune -o -name "*.mo" -print)
  )

  # Get elements
  decompose-load-elements

  # Process .mo files
  for t in ${templates[@]}; do
    cat $t | . $(which mo) > ${t%.*}
    chmod --reference $t ${t%.*}
    echo "$t -> ${t%.*}"
  done
}

# Finds the decompose directory in parents
#
# Parameters:
#   $1: return value (decompose directory location)
decompose-find-decompose-directory() {
  local current_dir=$(realpath .)
  while [[ ! -d "$current_dir/.decompose" && "$current_dir" != "/" ]]; do
    current_dir=$(realpath $current_dir/../)
  done

  # We hit the end. See if we found .decompose
  if [ -d "$current_dir/.decompose" ]; then
    eval "$1=$current_dir/.decompose"
    return 0
  fi

  # I guess we didn't find .decompose
  return 1
}

# Returns the project root directory
#
# Parameters:
#   $1: return value (project root location)
decompose-project-root() {
  local decompose_directory
  decompose-find-decompose-directory decompose_directory

  eval "$1=$(realpath $decompose_directory/../)"
}

# Create/collect configuration where necessary
decompose-bootstrap() {
  # Verify dependencies
  decompose-verify-dependencies
  if [ "$?" -ne "0" ]; then
    echo "Please install missing dependencies"
    exit 1
  fi

  local decompose_data_dir=$(realpath ~/.local/share/decompose)
  # Create ecosphere
  if [ ! -d "$decompose_data_dir/ecosphere" ]; then
    mkdir -p "$decompose_data_dir/ecosphere"
  fi
}

# Print dependencies that are missing
decompose-verify-dependencies() {
  local return_code
  local checks=('which' 'mo' 'echo' 'cat' 'mkdir' 'git' 'realpath' 'cp' 'find'
    'chmod' 'md5sum')

  for check in ${checks[@]}; do
    which $check >/dev/null 2>&1
    if [ "$?" -ne "0" ]; then
      echo "'$check' command is missing"
      return_code=1
      if [ "$check" == "which" ]; then break; fi
    fi
  done

  return $return_code
}

# Print version
decompose-version() {
  local version="0.5"
  echo "decompose v$version"
}

decompose-bootstrap
decompose-parse-parameters "$@"
