#!/bin/bash
# decompose functions
#
# Assume $DIR is defined as the root directory of the calling script.

#!/bin/bash
# Parse parameters and run the correct command.
#
# Parameters:
#   $1: decompose parameters
decompose-parse-parameters() {
  case $1 in
    "--init")
      decompose-init-command $2;;
    "--update")
      decompose-update-environment;;
    "--build")
      decompose-build;;
    "--version")
      decompose-version;;
    "--help")
      decompose-print-help;;
    "--completion")
      decompose-completion;;
    *)
      # Go through all environment commands
      local decompose_directory
      decompose-find-decompose-directory decompose_directory

      if [ -f $decompose_directory/environment/processes ]; then
        . $decompose_directory/environment/processes
        for p in "${DECOMPOSE_PROCESSES[@]}"
        do
          if [ "$1" == "$p" ]; then
            decompose-load-elements
            $p "${@:2}"
            exit 0
          fi
        done
      fi

      echo "Unknown parameter '$1'"
      decompose-print-help
      ;;
  esac
}

# Print help
decompose-print-help() {
  cat <<HELP_EOF
decompose - Development Environment Compose

Core commands:

--init <git_url>
  Initialize an environment from a git URL and name
--update
  Update the current environment
--build
  Build project files from templates
--version
  Print version
--help
  This message
HELP_EOF

  # Go through all environment commands
  local decompose_directory
  decompose-find-decompose-directory decompose_directory

  if [ -f $decompose_directory/environment/processes ]; then
    echo -e "\nEnvironment processes:\n"

    . $decompose_directory/environment/processes
    for p in "${DECOMPOSE_PROCESSES[@]}"; do
      echo "$p"
      "$p"_help
    done
  fi
}

# Return md5 hash of parameter $1
#
# Parameters:
#   $1: string to hash
#   $2: hash value returned
decompose-md5-hash() {
  local string_value=$1
  local __hash_value=$2

  local _hash=$(echo "$string_value" | md5sum)
  eval "$__hash_value=${_hash% -*}"
}

# Initialize the environment (.decompose directory)
#
# Paramaters:
#   $1: environment url
decompose-init-environment() {
  local environment_url=$1

  # Is environment parameter valid?
  if [ -z "$environment_url" ]; then
    echo "Please supply an environment url to initialize"
    return 1
  fi

  # Update git repository
  decompose-update-git-repository $environment_url

  # Copy files from clone to .decompose
  # Is environment created already?
  local decompose_directory
  decompose-find-decompose-directory decompose_directory
  if [ -d "$decompose_directory" ]; then
    echo ".decompose directory already exists here:"
    echo "$decompose_directory"
    exit 1
  fi

  echo "Initializing environment"

  # If .decompose-init exists then put .decompose in the right place
  local project_root
  decompose-project-root project_root
  if [ "$?" -gt "0" ]; then
    mkdir ".decompose"
    # Save .decompose-init
    echo "$environment_url" > .decompose-init
  else
    mkdir "$project_root/.decompose"
  fi

  # Project root will definetly exist now.
  decompose-project-root project_root

  # Copy environment files
  mkdir "$project_root/.decompose/environment"
  local decompose_data_dir=$(realpath ~/.local/share/decompose)
  local environment_hash
  decompose-md5-hash $environment_url environment_hash
  cp -r "$decompose_data_dir/ecosphere/$environment_hash/"* "$project_root/.decompose/environment"
}

# Initialize environment command
#
# Paramaters:
#   $1: environment url
decompose-init-command() {
  local environment_url=$1

  # Is environment parameter valid?
  if [ -z "$environment_url" ]; then
    echo "Please supply an environment url to initialize"
    exit 1
  fi

  # Create environment
  decompose-init-environment $environment_url

  # If error occured then quit
  if [ "$?" -gt "0" ]; then
    echo "Error occured initializing environment"
    exit 1
  fi

  # Copy skeleton to working directory
  cp -r .decompose/environment/skel/. ./
}

# Return 0 if .decompose exists, else return 1
decompose-directory-exists() {
  local decompose_directory
  decompose-find-decompose-directory decompose_directory

  # If .decompose is missing then return error code.
  if [ "$?" -gt "0"  ]; then
    return 1
  fi
  return 0
}

# Load elements
decompose-load-elements() {
  local decompose_directory
  decompose-find-decompose-directory decompose_directory

  # Load default settings and then overrides
  . $decompose_directory/environment/elements
  if [ -e $decompose_directory/elements ]; then
    . $decompose_directory/elements
  fi
}

# Updates a git repository
#
# Parameters
#   $1: git repository URL
decompose-update-git-repository() {
  local git_repo_url=$1

  local decompose_data_dir=$(realpath ~/.local/share/decompose)

  local git_repo_hash
  decompose-md5-hash $git_repo_url git_repo_hash
  if [ -d "$decompose_data_dir/ecosphere/$git_repo_hash" ]; then
    git -C "$decompose_data_dir/ecosphere/$git_repo_hash" pull
  else
    git clone $git_repo_url \
      "$decompose_data_dir/ecosphere/$git_repo_hash"
  fi
}

# Updates decompose environment
decompose-update-environment() {
  # If .decompose-init doesn't exist then there is nothing we can do
  local project_root
  decompose-project-root project_root
  if [ ! -e "$project_root/.decompose-init" ]; then
    echo "Cannot update '.decompose' because '.decompose-init' is missing"
    echo "Create a '.decompose-init' file with the URL to the environment URL"
    echo "Or delete the '.decompose' directory and run 'decompose --init' again"
    exit 1
  fi

  local environment_url=$(cat "$project_root/.decompose-init")

  # If .decompose directory doesn't exist initialize .decompose directory
  decompose-directory-exists
  if [ "$?" -gt "0" ]; then
    # Initialize .decompose
    decompose-init-environment $environment_url

    return "$?"
  fi

  # Update git repository
  decompose-update-git-repository $environment_url

  # Update environment
  local decompose_data_dir=$(realpath ~/.local/share/decompose)
  local decompose_directory
  decompose-find-decompose-directory decompose_directory
  local environment_hash
  decompose-md5-hash $environment_url environment_hash
  if [ -n "$decompose_directory" ]; then
    rm -r $decompose_directory/environment
    mkdir -p $decompose_directory/environment
    cp -r $decompose_data_dir/ecosphere/$environment_hash/* \
      $decompose_directory/environment
  fi
}

# Build project files from templates
decompose-build() {
  echo "Building project files from templates"
  # Find all .mo files
  local project_root
  decompose-project-root project_root
  local templates=(
    $(find $project_root -path "$project_root/.decompose" -prune -o -name "*.mo" -print)
  )

  # Get elements
  decompose-load-elements

  # Process .mo files
  for t in ${templates[@]}; do
    cat $t | . "$DIR/mo/mo" > ${t%.*}
    chmod --reference $t ${t%.*}
    echo "$t -> ${t%.*}"
  done
}
# Finds the decompose directory in parents
#
# Parameters:
#   $1: return value (decompose directory location)
decompose-find-decompose-directory() {
  local __decompose_directory=$1
  local decompose_root
  decompose-project-root decompose_root

  if [ -d "$decompose_root/.decompose" ]; then
    eval "$__decompose_directory=$decompose_root/.decompose"
    return 0
  fi
  return 1
}

# Returns the project root directory
#
# Parameters:
#   $1: return value (project root location)
decompose-project-root() {
  local __return_val=$1
  local current_dir=$(realpath .)
  while [[ ! -d "$current_dir/.decompose" && \
    ! -e "$current_dir/.decompose-init" &&  \
    "$current_dir" != "/" ]]; do
    current_dir=$(realpath $current_dir/../)
  done

  # We hit the end. See if we found .decompose or .decompose-init
  if [[ -d "$current_dir/.decompose" || -e "$current_dir/.decompose-init" ]]; then
    eval "$__return_val=$current_dir"
    return 0
  fi
  return 1
}

# Create/collect configuration where necessary
decompose-bootstrap() {
  # Verify dependencies
  decompose-verify-dependencies
  if [ "$?" -ne "0" ]; then
    echo "Please install missing dependencies"
    exit 1
  fi

  local decompose_data_dir=$(realpath ~/.local/share/decompose)
  # Create ecosphere
  if [ ! -d "$decompose_data_dir/ecosphere" ]; then
    mkdir -p "$decompose_data_dir/ecosphere"
  fi
}

# Print dependencies that are missing
decompose-verify-dependencies() {
  local return_code
  local checks=('which' 'echo' 'cat' 'mkdir' 'git' 'realpath' 'cp' 'find'
    'chmod' 'md5sum')

  for check in ${checks[@]}; do
    which $check >/dev/null 2>&1
    if [ "$?" -ne "0" ]; then
      echo "'$check' command is missing"
      return_code=1
      if [ "$check" == "which" ]; then break; fi
    fi
  done

  # Check that mo exists.
  if [ ! -e "$DIR/mo/mo" ]; then
    echo "'mo' is missing"
    return_code=1
  fi

  return $return_code
}

# Print version
decompose-version() {
  local version="0.7"
  echo "decompose v$version"
}
